spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/empleados_db
    username: empleados_user
    password: empleados_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true